# Generated by Django 4.0.4 on 2022-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_description_alter_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
