# Generated by Django 4.0.4 on 2022-05-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time',
            new_name='added_time',
        ),
    ]
