# Generated by Django 4.0.4 on 2022-05-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodo',
            old_name='task',
            new_name='tasks',
        ),
    ]
